<a href="https://colab.research.google.com/github/hyeminheather/python_programming/blob/main/Chap11_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy 불러오기

In [ ]:
import numpy as np

In [ ]:
a = np.arange(6)

In [ ]:
type(a)

numpy.ndarray

In [ ]:
print(type(a))

<class 'numpy.ndarray'>


In [ ]:
a

array([0, 1, 2, 3, 4, 5])

In [ ]:
a[0]

np.int64(0)

In [ ]:
a2 = a[np.newaxis,:] #2차원

In [ ]:
a2.shape

(1, 6)

In [ ]:
a.shape

(6,)

배열

In [ ]:
a=np.array([1,2,3,4,5,6])

In [ ]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [ ]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
a[0,1]

np.int64(2)

In [ ]:
a[0]

array([1, 2, 3, 4])

In [ ]:
a[2]

array([ 9, 10, 11, 12])

In [ ]:
a[2,1]

np.int64(10)

In [ ]:
a=np.array([1,2,3])

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.ones(3)

array([1., 1., 1.])

In [ ]:
np.empty(7)

array([4.34315866e-315, 0.00000000e+000, 4.44659081e-323,             nan,
       0.00000000e+000, 6.62626333e-310, 6.62626333e-310])

In [ ]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [ ]:
np.arange(2,10,2) #2에서 10까지 만들어주는데 2개씩 점프 # 근데 10은 출력안함

array([2, 4, 6, 8])

In [ ]:
np.linspace(0,10,num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
b = np.ones(2, dtype=np.float64)

In [ ]:
b

array([1., 1.])

adding removing sorting

In [ ]:
arr = np.array([2,1,5,3,7,5,6,8])
arr



array([2, 1, 5, 3, 7, 5, 6, 8])

In [ ]:
np.lexsort(arr)

np.int64(0)

In [ ]:
np.partition(arr)

TypeError: partition() missing 1 required positional argument: 'kth'

In [ ]:

np.sort(arr)

array([1, 2, 3, 5, 5, 6, 7, 8])

In [ ]:
arr = np.sort(arr)

In [ ]:
np.argsort(arr)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [ ]:
a= np.array([1,2,3,4,5])
b= np.array([5,6,7,8,9])

In [ ]:
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 5, 6, 7, 8, 9])

In [ ]:
x=np.array([[1,2],[3,4]])
y=np.array([[5,6]])

In [ ]:
np.concatenate((x,y))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
np.concatenate((x,y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
np.concatenate((x,y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])


In [ ]:
array_example

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [ ]:
array_example.ndim #디멘젠 차원

3

In [ ]:
array_example.size  # 요소의 개수

24

In [ ]:
array_example.shape #덩어리가 3개, 2개 행, 요소가 4개

(3, 2, 4)

In [ ]:
a= np.arange(6)

In [ ]:
print(a)

[0 1 2 3 4 5]


In [ ]:
a.reshape(2,3)  #numpy에 있는 자료라서 a. 이라고 쓸수있다 # 2 X 3으로 reshape

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
a=a.reshape(6)|

In [ ]:
np.reshape(a, shape=(1, 6), order='C')

TypeError: reshape() got an unexpected keyword argument 'shape'

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [ ]:
a2 = a[np.newaxis, :]
a2.shape
(1, 6)

(1, 6)

In [ ]:
row_vector = a[np.newaxis, :]
row_vector.shape

(1, 6)

In [ ]:
col_vector = a[:, np.newaxis]
col_vector.shape

(6, 1)

Indexing Slicing

In [ ]:
data = np.array([1, 2, 3])
data[1]

np.int64(2)

In [ ]:
data

array([1, 2, 3])

In [ ]:
data[1]

np.int64(2)

In [ ]:
data[0:2] #0부터 2 직전까지

array([1, 2])

In [ ]:
data[1:] #1부터 끝까지

array([2, 3])

In [ ]:
data[-2:] #끝에서 부터 두번째

array([2, 3])

In [ ]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
a>5

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [ ]:
a[a>5] #a 행렬에서 5보다 큰 것만 추출

array([ 6,  7,  8,  9, 10, 11, 12])

In [ ]:
a[a%2==0]

array([ 2,  4,  6,  8, 10, 12])

In [ ]:
a[(a>2)&(a<11)]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
b=np.nonzero(a<5) #
print(b)

(array([0, 0, 0, 0]), array([0, 1, 2, 3]))


In [ ]:
list(zip(b[0], b[1]))


[(np.int64(0), np.int64(0)),
 (np.int64(0), np.int64(1)),
 (np.int64(0), np.int64(2)),
 (np.int64(0), np.int64(3))]

In [ ]:
list_of_coordinates= list(zip(b[0], b[1]))

In [ ]:
for coord in list_of_coordinates:
  print(coord)

(np.int64(0), np.int64(0))
(np.int64(0), np.int64(1))
(np.int64(0), np.int64(2))
(np.int64(0), np.int64(3))


In [ ]:
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr1 = a[3:8]

In [ ]:
print(arr1)

[4 5 6 7 8]


In [ ]:
a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])

In [ ]:
np.vstack((a1,a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [ ]:
np.hstack((a1,a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [ ]:
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
a.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
a=np.arange(0,10).reshape(2,5)

In [ ]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
x=np.arange(1,25).reshape(2,12)

In [ ]:
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [ ]:
np.hsplit(x,3)[0]

array([[ 1,  2,  3,  4],
       [13, 14, 15, 16]])

In [ ]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
a[1,1]

np.int64(6)

In [ ]:
a[2,3]

np.int64(12)

In [ ]:
a[3:8]

array([], shape=(0, 4), dtype=int64)

In [ ]:
a[:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
a[2:]

array([[ 9, 10, 11, 12]])

In [ ]:
b1=a[0,:]

In [ ]:
b1

array([1, 2, 3, 4])

In [ ]:
b1[0] = 99

In [ ]:
b1

array([99,  2,  3,  4])

In [ ]:
a

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [ ]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
b1=a[0,:].copy()

In [ ]:
b1

array([1, 2, 3, 4])

In [ ]:
b1[0] = 99

In [ ]:
b1

array([99,  2,  3,  4])

In [ ]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

연산

In [220]:
data = np.array([1, 2])

In [221]:
ones = data = np.array([1, 2])
ones = np.ones(2, dtype=int)
data + ones

array([2, 3])

In [228]:
a = np.array([1, 2, 3, 4])
a.sum()

np.int64(10)

In [231]:
b=[1,321,3,4]
b.sort()

In [232]:
b

[1, 3, 4, 321]

In [237]:
b = np.array([[1, 1], [2, 2]])
b

array([[1, 1],
       [2, 2]])

In [234]:
b.sum(axis=0) # 0은 행

array([3, 3])

In [235]:
b.sum(axis=1) # 1은 열

array([2, 4])

In [238]:
data = np.array([1.0, 2.0])
data * 1.6

array([1.6, 3.2])

In [240]:
a.max()

np.int64(4)

In [241]:
a.min()

np.int64(1)

In [249]:
b = np.array([[1, 1], [2, 2]])


In [250]:
b.min()

np.int64(1)

In [251]:
b.min(axis=0)

array([1, 1])